sudo: false
language: node_js

node_js:
  - '8'

os:
  - osx
  - linux

matrix:
  fast_finish: true

notifications:
  email: false

before_install:
  - node --version

install:
  - npm install

script:
  - npm test
